name: 'SSM Send Command Action'
description: 'Send commands to an EC2 instance via AWS SSM'
author: 'Kayoung Yoon'

inputs:
  instanceId:
    description: 'The ID of the EC2 instance you want to connect to'
    required: false
  instanceName:
    description: 'The name of the EC2 instance you want to connect to'
    required: false
  workingDirectory:
    description: 'The working directory where you want to execute commands'
    required: true
  commands:
    description: 'The commands you want to execute on the instance'
    required: true

outputs:
  commandId:
    description: 'The ID of the executed command'

runs:
  using: node20
  main: dist/index.js
